version: "4.0"
services:
  update-api:
    build: .
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - .:/app
      - ${HOST_COMPOSE_PATH}:/mnt/project
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker:/root/.docker